const clubs = [
  {
    slug: 'slavia-praha',
    logo: 'https://upload.wikimedia.org/wikipedia/en/8/82/SK_Slavia_Prague_logo.svg',
    name: 'SK Slavia Praha',
    city: 'Praha',
    abbr: 'SLA',
    color: '#CC0000',
    keywords: ['Slavia', 'Slavie', 'Slavii', 'Slavií', 'SK Slavia', 'Slavia Praha', 'slávisté', 'sešívaní', 'vršovický'],
  },
  {
    slug: 'sparta-praha',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f5/AC_Sparta_Prague_logo.svg',
    name: 'AC Sparta Praha',
    city: 'Praha',
    abbr: 'SPA',
    color: '#AC1A2F',
    keywords: ['Sparta', 'Sparty', 'Spartě', 'Spartou', 'AC Sparta', 'Sparta Praha', 'sparťané', 'letenský', 'letenští'],
  },
  {
    slug: 'viktoria-plzen',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/37/FC_Viktoria_Plze%C5%88_logo.svg',
    name: 'FC Viktoria Plzeň',
    city: 'Plzeň',
    abbr: 'PLZ',
    color: '#003087',
    keywords: ['Plzeň', 'Plzně', 'Plzni', 'Plzní', 'Viktoria Plzeň', 'FC Viktoria', 'plzeňský', 'plzeňští', 'Viktorka'],
  },
  {
    slug: 'banik-ostrava',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b5/FC_Banik_Ostrava_logo.svg',
    name: 'FC Baník Ostrava',
    city: 'Ostrava',
    abbr: 'BAO',
    color: '#005CA9',
    keywords: ['Baník', 'Baníku', 'Baníkem', 'Baník Ostrava', 'FC Baník', 'ostravský', 'ostravští', 'baníkovci'],
  },
  {
    slug: 'sigma-olomouc',
    logo: 'https://upload.wikimedia.org/wikipedia/en/e/e4/SK_Sigma_Olomouc_logo.svg',
    name: 'SK Sigma Olomouc',
    city: 'Olomouc',
    abbr: 'OLO',
    color: '#003366',
    keywords: ['Sigma', 'Sigmy', 'Sigmě', 'Sigmou', 'Sigma Olomouc', 'SK Sigma', 'olomoucký', 'olomoučtí'],
  },
  {
    slug: 'bohemians-1905',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/db/Bohemians_1905_logo.svg',
    name: 'Bohemians Praha 1905',
    city: 'Praha',
    abbr: 'BOH',
    color: '#007A33',
    keywords: ['Bohemians', 'Bohemians 1905', 'Bohemce', 'Bohemka', 'Bohemky', 'Bohemkou', 'klokani', 'klokanů'],
  },
  {
    slug: 'slovan-liberec',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/5d/FC_Slovan_Liberec_logo.svg',
    name: 'FC Slovan Liberec',
    city: 'Liberec',
    abbr: 'LIB',
    color: '#003DA5',
    keywords: ['Liberec', 'Liberce', 'Liberci', 'Libercem', 'Slovan Liberec', 'FC Slovan', 'liberecký', 'liberečtí'],
  },
  {
    slug: 'slovacko',
    logo: 'https://upload.wikimedia.org/wikipedia/en/c/c4/FC_Slova%CC%81cko_logo.svg',
    name: 'FC Slovácko',
    city: 'Uherské Hradiště',
    abbr: 'SLO',
    color: '#C8500A',
    keywords: ['Slovácko', 'Slovácka', 'Slovácku', 'Slováckem', 'FC Slovácko', 'Uherské Hradiště', 'uherskohradišťský'],
  },
  {
    slug: 'mlada-boleslav',
    logo: 'https://upload.wikimedia.org/wikipedia/en/7/7c/FK_Mlad%C3%A1_Boleslav_logo.svg',
    name: 'FK Mladá Boleslav',
    city: 'Mladá Boleslav',
    abbr: 'MLB',
    color: '#005BAC',
    keywords: ['Boleslav', 'Boleslavy', 'Boleslavi', 'Boleslaví', 'Mladá Boleslav', 'FK Mladá Boleslav', 'boleslavský', 'boleslavští'],
  },
  {
    slug: 'jablonec',
    logo: 'https://upload.wikimedia.org/wikipedia/en/1/16/FK_Jablonec_logo.svg',
    name: 'FK Jablonec',
    city: 'Jablonec n. N.',
    abbr: 'JAB',
    color: '#F7A600',
    keywords: ['Jablonec', 'Jablonce', 'Jablonci', 'Jabloncem', 'FK Jablonec', 'jablonecký', 'jablonečtí'],
  },
  {
    slug: 'teplice',
    logo: 'https://upload.wikimedia.org/wikipedia/en/5/55/FK_Teplice_logo.svg',
    name: 'FK Teplice',
    city: 'Teplice',
    abbr: 'TEP',
    color: '#C8A200',
    keywords: ['Teplice', 'Teplic', 'Teplicích', 'Teplicema', 'Teplicím', 'Teplického', 'FK Teplice', 'teplický', 'tepličtí'],
  },
  {
    slug: 'karvina',
    logo: 'https://upload.wikimedia.org/wikipedia/en/d/d6/MFK_Karvin%C3%A1_logo.svg',
    name: 'MFK Karviná',
    city: 'Karviná',
    abbr: 'KAR',
    color: '#00529B',
    keywords: ['Karviná', 'Karviné', 'Karvinou', 'MFK Karviná', 'karvinský', 'karvinští'],
  },
  {
    slug: 'hradec-kralove',
    logo: 'https://upload.wikimedia.org/wikipedia/en/8/83/FC_Hradec_Kr%C3%A1lov%C3%A9_logo.svg',
    name: 'FC Hradec Králové',
    city: 'Hradec Králové',
    abbr: 'HRA',
    color: '#CC0000',
    keywords: ['Hradec', 'Hradce', 'Hradci', 'Hradcem', 'Hradec Králové', 'FC Hradec', 'hradecký', 'hradečtí'],
  },
  {
    slug: 'ceske-budejovice',
    logo: 'https://upload.wikimedia.org/wikipedia/en/b/b7/SK_Dynamo_%C4%8C._Bud%C4%9Bjovice_logo.svg',
    name: 'SK Dynamo Č. Budějovice',
    city: 'České Budějovice',
    abbr: 'DYN',
    color: '#1A1A1A',
    keywords: ['Dynamo', 'Dynama', 'Budějovice', 'Budějovic', 'Budějovicích', 'Dynamo Budějovice', 'budějovický', 'budějovičtí'],
  },
  {
    slug: 'zbrojovka-brno',
    logo: 'https://upload.wikimedia.org/wikipedia/en/0/0e/FC_Zbrojovka_Brno_logo.svg',
    name: 'FC Zbrojovka Brno',
    city: 'Brno',
    abbr: 'ZBR',
    color: '#003DA5',
    keywords: ['Zbrojovka', 'Zbrojovky', 'Zbrojovce', 'Zbrojovkou', 'Zbrojovka Brno', 'FC Zbrojovka', 'brněnský fotbal'],
  },
  {
    slug: 'pardubice',
    name: 'FK Pardubice',
    city: 'Pardubice',
    abbr: 'PAR',
    color: '#002F6C',
    keywords: ['Pardubice', 'Pardubic', 'Pardubicích', 'Pardubicemi', 'FK Pardubice', 'pardubický'],
  },
  {
    slug: 'zlin',
    name: 'FC Trinity Zlín',
    city: 'Zlín',
    abbr: 'ZLN',
    color: '#FFD700',
    keywords: ['Zlín', 'Zlína', 'Zlínu', 'Zlínem', 'FC Zlín', 'Trinity Zlín', 'zlínský', 'Fastav'],
  },
  {
    slug: 'dukla-praha',
    logo: 'https://upload.wikimedia.org/wikipedia/en/3/34/FK_Dukla_Praha_logo.svg',
    name: 'FK Dukla Praha',
    city: 'Praha',
    abbr: 'DUK',
    color: '#CC9900',
    keywords: ['Dukla', 'Dukly', 'Dukle', 'Duklou', 'Dukla Praha', 'FK Dukla'],
  },
];

module.exports = clubs;
