const clubs = [
  {
    slug: 'slavia-praha',
    name: 'SK Slavia Praha',
    city: 'Praha',
    abbr: 'SLA',
    color: '#CC0000',
    keywords: ['Slavia', 'SK Slavia', 'Slavia Praha', 'slávisté', 'sešívaní', 'vršovický'],
  },
  {
    slug: 'sparta-praha',
    name: 'AC Sparta Praha',
    city: 'Praha',
    abbr: 'SPA',
    color: '#AC1A2F',
    keywords: ['Sparta', 'AC Sparta', 'Sparta Praha', 'sparťané', 'letenští'],
  },
  {
    slug: 'viktoria-plzen',
    name: 'FC Viktoria Plzeň',
    city: 'Plzeň',
    abbr: 'PLZ',
    color: '#003087',
    keywords: ['Plzeň', 'Viktoria Plzeň', 'FC Viktoria', 'plzeňští', 'Viktorka'],
  },
  {
    slug: 'banik-ostrava',
    name: 'FC Baník Ostrava',
    city: 'Ostrava',
    abbr: 'BAO',
    color: '#005CA9',
    keywords: ['Baník', 'Baník Ostrava', 'FC Baník', 'ostravští', 'baníkovci'],
  },
  {
    slug: 'sigma-olomouc',
    name: 'SK Sigma Olomouc',
    city: 'Olomouc',
    abbr: 'OLO',
    color: '#003366',
    keywords: ['Sigma', 'Sigma Olomouc', 'SK Sigma', 'olomoučtí'],
  },
  {
    slug: 'bohemians-1905',
    name: 'Bohemians Praha 1905',
    city: 'Praha',
    abbr: 'BOH',
    color: '#007A33',
    keywords: ['Bohemians', 'Bohemians 1905', 'Bohemka', 'klokani'],
  },
  {
    slug: 'slovan-liberec',
    name: 'FC Slovan Liberec',
    city: 'Liberec',
    abbr: 'LIB',
    color: '#003DA5',
    keywords: ['Liberec', 'Slovan Liberec', 'FC Slovan', 'liberečtí'],
  },
  {
    slug: 'slovacko',
    name: 'FC Slovácko',
    city: 'Uherské Hradiště',
    abbr: 'SLO',
    color: '#C8500A',
    keywords: ['Slovácko', 'FC Slovácko', 'Uherské Hradiště'],
  },
  {
    slug: 'mlada-boleslav',
    name: 'FK Mladá Boleslav',
    city: 'Mladá Boleslav',
    abbr: 'MLB',
    color: '#005BAC',
    keywords: ['Mladá Boleslav', 'FK Mladá Boleslav', 'Boleslav', 'boleslavští'],
  },
  {
    slug: 'jablonec',
    name: 'FK Jablonec',
    city: 'Jablonec n. N.',
    abbr: 'JAB',
    color: '#F7A600',
    keywords: ['Jablonec', 'FK Jablonec', 'jablonečtí'],
  },
  {
    slug: 'teplice',
    name: 'FK Teplice',
    city: 'Teplice',
    abbr: 'TEP',
    color: '#C8A200',
    keywords: ['Teplice', 'FK Teplice', 'tepličtí'],
  },
  {
    slug: 'karvina',
    name: 'MFK Karviná',
    city: 'Karviná',
    abbr: 'KAR',
    color: '#00529B',
    keywords: ['Karviná', 'MFK Karviná', 'karvinští'],
  },
  {
    slug: 'hradec-kralove',
    name: 'FC Hradec Králové',
    city: 'Hradec Králové',
    abbr: 'HRA',
    color: '#CC0000',
    keywords: ['Hradec Králové', 'FC Hradec', 'hradečtí', 'Hradec'],
  },
  {
    slug: 'ceske-budejovice',
    name: 'SK Dynamo Č. Budějovice',
    city: 'České Budějovice',
    abbr: 'DYN',
    color: '#1A1A1A',
    keywords: ['Dynamo', 'Dynamo České Budějovice', 'Dynamo Budějovice', 'budějovičtí', 'České Budějovice'],
  },
  {
    slug: 'zbrojovka-brno',
    name: 'FC Zbrojovka Brno',
    city: 'Brno',
    abbr: 'ZBR',
    color: '#003DA5',
    keywords: ['Zbrojovka', 'Zbrojovka Brno', 'FC Zbrojovka', 'brněnský fotbal'],
  },
  {
    slug: 'dukla-praha',
    name: 'FK Dukla Praha',
    city: 'Praha',
    abbr: 'DUK',
    color: '#CC9900',
    keywords: ['Dukla', 'Dukla Praha', 'FK Dukla'],
  },
];

module.exports = clubs;
